export interface SeedUser {
  key: string;
  name: string;
  email: string;
  password: string;
  role: "learner" | "store_manager" | "trainer" | "district_leader" | "admin";
  title: string;
  locationKey: string | null;
  teamKey: string | null;
  experienceLevel: string;
  retailEnvironment: string;
  careerGoal: string;
  primarySkillGoal: string;
  weeklyAvailabilityHours: number;
  region: string;
  market: string;
  onboarded: boolean;
}

export const DEMO_PASSWORD = "Aurelia2026!";

export const SEED_USERS: SeedUser[] = [
  {
    key: "new_associate",
    name: "Mia Alvarez",
    email: "mia.alvarez@aureliademo.com",
    password: DEMO_PASSWORD,
    role: "learner",
    title: "New Jewelry Associate",
    locationKey: "harbour_view",
    teamKey: "harbour_view_sales",
    experienceLevel: "0-1 years",
    retailEnvironment: "luxury_boutique",
    careerGoal: "sales_associate",
    primarySkillGoal: "diamond_gemstone_knowledge",
    weeklyAvailabilityHours: 3,
    region: "North America",
    market: "Coastal Metro",
    onboarded: true,
  },
  {
    key: "bridal_specialist",
    name: "Priya Natarajan",
    email: "priya.natarajan@aureliademo.com",
    password: DEMO_PASSWORD,
    role: "learner",
    title: "Bridal Specialist",
    locationKey: "bridal_house",
    teamKey: "bridal_house_sales",
    experienceLevel: "3-5 years",
    retailEnvironment: "bridal",
    careerGoal: "bridal_specialist",
    primarySkillGoal: "bridal",
    weeklyAvailabilityHours: 4,
    region: "North America",
    market: "Coastal Metro",
    onboarded: true,
  },
  {
    key: "luxury_advisor",
    name: "Julian Cross",
    email: "julian.cross@aureliademo.com",
    password: DEMO_PASSWORD,
    role: "learner",
    title: "Luxury Client Advisor",
    locationKey: "harbour_view",
    teamKey: "harbour_view_sales",
    experienceLevel: "5+ years",
    retailEnvironment: "luxury_boutique",
    careerGoal: "sales_associate",
    primarySkillGoal: "clienteling",
    weeklyAvailabilityHours: 2,
    region: "North America",
    market: "Coastal Metro",
    onboarded: true,
  },
  {
    key: "cruise_specialist",
    name: "Ana Bautista",
    email: "ana.bautista@aureliademo.com",
    password: DEMO_PASSWORD,
    role: "learner",
    title: "Cruise Retail Specialist",
    locationKey: "ocean_passage",
    teamKey: "ocean_passage_sales",
    experienceLevel: "1-3 years",
    retailEnvironment: "cruise_travel",
    careerGoal: "sales_associate",
    primarySkillGoal: "sales_conversations",
    weeklyAvailabilityHours: 3,
    region: "Caribbean",
    market: "Cruise Circuit",
    onboarded: true,
  },
  {
    key: "gemologist_seller",
    name: "Devon Osei",
    email: "devon.osei@aureliademo.com",
    password: DEMO_PASSWORD,
    role: "learner",
    title: "Gemologist-Seller",
    locationKey: "harbour_view",
    teamKey: "harbour_view_sales",
    experienceLevel: "5+ years",
    retailEnvironment: "luxury_boutique",
    careerGoal: "gemologist_seller",
    primarySkillGoal: "diamond_gemstone_knowledge",
    weeklyAvailabilityHours: 5,
    region: "North America",
    market: "Coastal Metro",
    onboarded: true,
  },
  {
    key: "store_manager",
    name: "Renee Whitfield",
    email: "renee.whitfield@aureliademo.com",
    password: DEMO_PASSWORD,
    role: "store_manager",
    title: "Store Manager, Harbour View",
    locationKey: "harbour_view",
    teamKey: "harbour_view_sales",
    experienceLevel: "5+ years",
    retailEnvironment: "luxury_boutique",
    careerGoal: "store_manager",
    primarySkillGoal: "coaching",
    weeklyAvailabilityHours: 4,
    region: "North America",
    market: "Coastal Metro",
    onboarded: true,
  },
  {
    key: "district_leader",
    name: "Marcus Ferreira",
    email: "marcus.ferreira@aureliademo.com",
    password: DEMO_PASSWORD,
    role: "district_leader",
    title: "District Leader, Coastal Region",
    locationKey: null,
    teamKey: null,
    experienceLevel: "5+ years",
    retailEnvironment: "luxury_boutique",
    careerGoal: "district_leader",
    primarySkillGoal: "leadership",
    weeklyAvailabilityHours: 3,
    region: "North America",
    market: "Coastal Metro",
    onboarded: true,
  },
  {
    key: "trainer",
    name: "Sofia Marchetti",
    email: "sofia.marchetti@aureliademo.com",
    password: DEMO_PASSWORD,
    role: "trainer",
    title: "Sales Trainer & L&D Lead",
    locationKey: null,
    teamKey: null,
    experienceLevel: "5+ years",
    retailEnvironment: "luxury_boutique",
    careerGoal: "trainer",
    primarySkillGoal: "coaching",
    weeklyAvailabilityHours: 6,
    region: "North America",
    market: "Coastal Metro",
    onboarded: true,
  },
  {
    key: "admin",
    name: "Taylor Kim",
    email: "taylor.kim@aureliademo.com",
    password: DEMO_PASSWORD,
    role: "admin",
    title: "Platform Administrator",
    locationKey: null,
    teamKey: null,
    experienceLevel: "5+ years",
    retailEnvironment: "luxury_boutique",
    careerGoal: "trainer",
    primarySkillGoal: "store_operations",
    weeklyAvailabilityHours: 5,
    region: "North America",
    market: "Coastal Metro",
    onboarded: true,
  },
  // Additional learners on manager's team, for a richer team roster
  {
    key: "learner_extra_1",
    name: "Grace Liu",
    email: "grace.liu@aureliademo.com",
    password: DEMO_PASSWORD,
    role: "learner",
    title: "Jewelry Associate",
    locationKey: "harbour_view",
    teamKey: "harbour_view_sales",
    experienceLevel: "1-3 years",
    retailEnvironment: "luxury_boutique",
    careerGoal: "sales_associate",
    primarySkillGoal: "sales_conversations",
    weeklyAvailabilityHours: 3,
    region: "North America",
    market: "Coastal Metro",
    onboarded: true,
  },
  {
    key: "learner_extra_2",
    name: "Owen Bennett",
    email: "owen.bennett@aureliademo.com",
    password: DEMO_PASSWORD,
    role: "learner",
    title: "Jewelry Associate",
    locationKey: "harbour_view",
    teamKey: "harbour_view_sales",
    experienceLevel: "0-1 years",
    retailEnvironment: "luxury_boutique",
    careerGoal: "sales_associate",
    primarySkillGoal: "objection_handling",
    weeklyAvailabilityHours: 2,
    region: "North America",
    market: "Coastal Metro",
    onboarded: true,
  },
  {
    key: "learner_extra_3",
    name: "Isabella Moreau",
    email: "isabella.moreau@aureliademo.com",
    password: DEMO_PASSWORD,
    role: "learner",
    title: "Bridal Associate",
    locationKey: "bridal_house",
    teamKey: "bridal_house_sales",
    experienceLevel: "1-3 years",
    retailEnvironment: "bridal",
    careerGoal: "bridal_specialist",
    primarySkillGoal: "bridal",
    weeklyAvailabilityHours: 4,
    region: "North America",
    market: "Coastal Metro",
    onboarded: true,
  },
];
